version: '3.8'
services:
  backend:
    build: .
    container_name: chat-backend
    ports:
      - "8000:8000"
      - "8080:8080"
    networks:
      - chat-network

  frontend:
    build: ./src/main/frontend
    container_name: chat-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - chat-network

networks:
  chat-network:
    driver: bridge